services:
  web:
    build: .
    ports:
      - 8000:8000
    environment:
      - DATABASE_URL=postgresql+asyncpg://postgres:postgres@db:5432/fastapi_dev
      - DEV_DATABASE_URL=postgresql+asyncpg://postgres:postgres@db:5432/fastapi_dev
    volumes:
      - .:/app
    depends_on:
      db:
        condition: service_healthy
    command: uvicorn src.main:app --host 0.0.0.0 --port 8000 --reload

  db:
    image: postgres:16
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=fastapi_dev
    ports:
      - 54321:5432
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d fastapi_dev"]
      interval: 5s
      timeout: 5s
      retries: 5

volumes:
  postgres_data:
